pars: pars::net::context Class Reference
pars::net::context Class Reference
#include <context.h>
Public Member Functions
context (ev::enqueuer &r, nngxx::ctx &&c, const net::socket &s)
~context ()
operator tool_view ()
void set_options (context_opt opts)
context_opt options () const
void send_aio (nngxx::aio_view &a)
void recv_aio (nngxx::aio_view &a)
template<ev::event_c event_t>
void send (event_t ev, pipe p)
void recv ()
void stop ()
int id () const
int socket_id () const
const net::socket & sock () const
auto format_to (fmt::format_context &ctx) const -> decltype(ctx.out())
Detailed Description
Definition at line 43 of file context.h.
Constructor & Destructor Documentation
context()
pars::net::context::context (ev::enqueuer & r, nngxx::ctx && c, const net::socket & s) inline
Definition at line 46 of file context.h.
    : router_m{r}
    , ctx_m{std::move(c)}
    , sock_m{s}
  {
  }
~context()
pars::net::context::~context () inline
Definition at line 53 of file context.h.
{ stop(); }
References stop().
Member Function Documentation
format_to()
auto pars::net::context::format_to (fmt::format_context & ctx) const -> decltype(ctx.out()) inline
Definition at line 92 of file context.h.
  {
    return fmt::format_to(ctx.out(), "context #{}", id());
  }
id()
int pars::net::context::id () const inline
Definition at line 86 of file context.h.
{ return ctx_m.id(); }
operator tool_view()
pars::net::context::operator tool_view () inline
Definition at line 55 of file context.h.
{ return tool_view{ctx_m}; }
options()
context_opt pars::net::context::options () const inline
Definition at line 66 of file context.h.
  {
    return {.recv_timeout = ctx_m.get_recv_timeout().value_or_abort(),
            .send_timeout = ctx_m.get_send_timeout().value_or_abort()};
  }
recv()
void pars::net::context::recv () inline
Definition at line 82 of file context.h.
{ op_m.recv(router_m, *this); }
Referenced by pars::net::context_registry::start_recv().
recv_aio()
void pars::net::context::recv_aio (nngxx::aio_view & a) inline
Definition at line 74 of file context.h.
{ ctx_m.recv(a); }
send()
template<ev::event_c event_t> void pars::net::context::send (event_t ev, pipe p) inline
Definition at line 77 of file context.h.
  {
    op_m.send(router_m, *this, p, ev);
  }
send_aio()
void pars::net::context::send_aio (nngxx::aio_view & a) inline
Definition at line 72 of file context.h.
{ ctx_m.send(a); }
set_options()
void pars::net::context::set_options (context_opt opts) inline
Definition at line 57 of file context.h.
  {
    if (opts.recv_timeout)
      ctx_m.set_recv_timeout(*opts.recv_timeout).or_abort();
    if (opts.send_timeout)
      ctx_m.set_send_timeout(*opts.send_timeout).or_abort();
  }
References pars::net::context_opt::recv_timeout, and pars::net::context_opt::send_timeout.
sock()
const net::socket & pars::net::context::sock () const inline
Definition at line 90 of file context.h.
{ return sock_m; }
socket_id()
int pars::net::context::socket_id () const inline
Definition at line 88 of file context.h.
{ return sock_m.id(); }
stop()
void pars::net::context::stop () inline
Definition at line 84 of file context.h.
{ op_m.stop(); }
Referenced by ~context().
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/context.h