pars: pars Namespace Reference
pars Namespace Reference
Namespaces
namespace app
namespace comp
namespace ev
namespace f
namespace net
Typedefs
using milli = std::chrono::duration<nng_duration, std::milli>
Enumerations
enum class error { success = 0 }
enum class lf {
app = 1 , comp = 2 , event = 4 , net = 8 ,
user = 1073741824
}
Functions
std::error_code make_error_code (pars::error e) noexcept
template<typename... args_t>
void log (spdlog::source_loc loc, pars::lf lf, spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void log (pars::lf lf, spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void log (spdlog::source_loc loc, spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void log (spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void trace (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void trace (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void trace (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void trace (spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void debug (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void debug (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void debug (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void debug (spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void info (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void info (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void info (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void info (spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void warn (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void warn (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void warn (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void warn (spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void err (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void err (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void err (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void err (spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void critical (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void critical (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void critical (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args)
template<typename... args_t>
void critical (spdlog::format_string_t< args_t... > fmt, args_t &&... args)
Typedef Documentation
milli
using pars::milli = std::chrono::duration<nng_duration, std::milli>
Definition at line 47 of file init.h.
Enumeration Type Documentation
error
enum class pars::error strong
Enumerator
success
Definition at line 40 of file err.h.
{
  success = 0
};
lf
enum class pars::lf strong
Enumerator
app
comp
event
net
user
Definition at line 37 of file flags.h.
{
  app = 1,
  comp = 2,
  event = 4,
  net = 8,
  user = 1073741824,
};
Function Documentation
critical() [1/4]
template<typename... args_t> void pars::critical (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 249 of file log.h.
{
  ::pars::log(lf, spdlog::level::critical, fmt, std::forward<args_t>(args)...);
}
References log().
critical() [2/4]
template<typename... args_t> void pars::critical (spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 263 of file log.h.
{
  ::pars::log(spdlog::level::critical, fmt, std::forward<args_t>(args)...);
}
References log().
critical() [3/4]
template<typename... args_t> void pars::critical (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 241 of file log.h.
{
  ::pars::log(lf, loc, spdlog::level::critical, fmt,
              std::forward<args_t>(args)...);
}
References log().
critical() [4/4]
template<typename... args_t> void pars::critical (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 256 of file log.h.
{
  ::pars::log(loc, spdlog::level::critical, fmt, std::forward<args_t>(args)...);
}
References log().
debug() [1/4]
template<typename... args_t> void pars::debug (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 140 of file log.h.
{
  ::pars::log(lf, spdlog::level::debug, fmt, std::forward<args_t>(args)...);
}
References log().
debug() [2/4]
template<typename... args_t> void pars::debug (spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 154 of file log.h.
{
  ::pars::log(spdlog::level::debug, fmt, std::forward<args_t>(args)...);
}
References log().
debug() [3/4]
template<typename... args_t> void pars::debug (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 132 of file log.h.
{
  ::pars::log(loc, lf, spdlog::level::debug, fmt,
              std::forward<args_t>(args)...);
}
References log().
Referenced by pars::ev::runner::associate_job_to_pipe(), pars::app::state_machine< state_t >::commit(), pars::app::resources< key_t, resource_t, mutex_t >::emplace(), pars::ev::runner::exec(), pars::app::state_machine< state_t >::next(), pars::net::op::recv(), pars::app::state_machine< state_t >::reset(), pars::app::state_machine< state_t >::rollback(), pars::net::op::send(), pars::ev::serialize::to_event(), and pars::ev::serialize::to_network().
debug() [4/4]
template<typename... args_t> void pars::debug (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 147 of file log.h.
{
  ::pars::log(loc, spdlog::level::debug, fmt, std::forward<args_t>(args)...);
}
References log().
err() [1/4]
template<typename... args_t> void pars::err (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 221 of file log.h.
{
  ::pars::log(lf, spdlog::level::err, fmt, std::forward<args_t>(args)...);
}
References log().
err() [2/4]
template<typename... args_t> void pars::err (spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 235 of file log.h.
{
  ::pars::log(spdlog::level::err, fmt, std::forward<args_t>(args)...);
}
References log().
err() [3/4]
template<typename... args_t> void pars::err (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 214 of file log.h.
{
  ::pars::log(loc, lf, spdlog::level::err, fmt, std::forward<args_t>(args)...);
}
References log().
Referenced by pars::net::op::abort(), pars::ev::runner::exec(), pars::net::op::recv(), pars::app::single< component_type >::run(), and pars::net::op::send().
err() [4/4]
template<typename... args_t> void pars::err (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 228 of file log.h.
{
  ::pars::log(loc, spdlog::level::err, fmt, std::forward<args_t>(args)...);
}
References log().
info() [1/4]
template<typename... args_t> void pars::info (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 167 of file log.h.
{
  ::pars::log(lf, spdlog::level::info, fmt, std::forward<args_t>(args)...);
}
References log().
info() [2/4]
template<typename... args_t> void pars::info (spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 181 of file log.h.
{
  ::pars::log(spdlog::level::info, fmt, std::forward<args_t>(args)...);
}
References log().
info() [3/4]
template<typename... args_t> void pars::info (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 160 of file log.h.
{
  ::pars::log(loc, lf, spdlog::level::info, fmt, std::forward<args_t>(args)...);
}
References log().
info() [4/4]
template<typename... args_t> void pars::info (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 174 of file log.h.
{
  ::pars::log(loc, spdlog::level::info, fmt, std::forward<args_t>(args)...);
}
References log().
log() [1/4]
template<typename... args_t> void pars::log (pars::lf lf, spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 79 of file log.h.
{
  if constexpr (pars_log_enabled)
  {
    if (pars_log_flags & lf)
      ::spdlog::log(lvl, fmt, std::forward<args_t>(args)...);
  }
}
log() [2/4]
template<typename... args_t> void pars::log (spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 97 of file log.h.
{
  ::pars::log(pars::lf::user, lvl, fmt, std::forward<args_t>(args)...);
}
References log(), and user.
log() [3/4]
template<typename... args_t> void pars::log (spdlog::source_loc loc, pars::lf lf, spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 67 of file log.h.
{
  if constexpr (pars_log_enabled)
  {
    if (pars_log_flags & lf)
      ::spdlog::log(loc, lvl, fmt, std::forward<args_t>(args)...);
  }
}
Referenced by critical(), critical(), critical(), critical(), debug(), debug(), debug(), debug(), err(), err(), err(), err(), info(), info(), info(), info(), log(), log(), trace(), trace(), trace(), trace(), warn(), warn(), warn(), and warn().
log() [4/4]
template<typename... args_t> void pars::log (spdlog::source_loc loc, spdlog::level::level_enum lvl, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 90 of file log.h.
{
  ::pars::log(loc, pars::lf::user, lvl, fmt, std::forward<args_t>(args)...);
}
References log(), and user.
make_error_code()
std::error_code pars::make_error_code (pars::error e) inline noexcept
Definition at line 66 of file err.h.
{
  return std::error_code(static_cast<int>(e), pars::error_category());
}
trace() [1/4]
template<typename... args_t> void pars::trace (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 112 of file log.h.
{
  ::pars::log(lf, spdlog::level::trace, fmt, std::forward<args_t>(args)...);
}
References log().
trace() [2/4]
template<typename... args_t> void pars::trace (spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 126 of file log.h.
{
  ::pars::log(spdlog::level::trace, fmt, std::forward<args_t>(args)...);
}
References log().
trace() [3/4]
template<typename... args_t> void pars::trace (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 104 of file log.h.
{
  ::pars::log(loc, lf, spdlog::level::trace, fmt,
              std::forward<args_t>(args)...);
}
References log().
trace() [4/4]
template<typename... args_t> void pars::trace (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 119 of file log.h.
{
  ::pars::log(loc, spdlog::level::trace, fmt, std::forward<args_t>(args)...);
}
References log().
warn() [1/4]
template<typename... args_t> void pars::warn (pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 194 of file log.h.
{
  ::pars::log(lf, spdlog::level::warn, fmt, std::forward<args_t>(args)...);
}
References log().
warn() [2/4]
template<typename... args_t> void pars::warn (spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 208 of file log.h.
{
  ::pars::log(spdlog::level::warn, fmt, std::forward<args_t>(args)...);
}
References log().
warn() [3/4]
template<typename... args_t> void pars::warn (spdlog::source_loc loc, pars::lf lf, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 187 of file log.h.
{
  ::pars::log(loc, lf, spdlog::level::warn, fmt, std::forward<args_t>(args)...);
}
References log().
warn() [4/4]
template<typename... args_t> void pars::warn (spdlog::source_loc loc, spdlog::format_string_t< args_t... > fmt, args_t &&... args) inline
Definition at line 201 of file log.h.
{
  ::pars::log(loc, spdlog::level::warn, fmt, std::forward<args_t>(args)...);
}
References log().