pars: clev Namespace Reference
clev Namespace Reference
Classes
struct exception
struct expected
struct expected< void >
struct iface
struct iface< nng_aio * >
struct iface< nng_ctx >
struct iface< nng_dialer >
struct iface< nng_listener >
struct iface< nng_msg * >
struct iface< nng_pipe >
struct iface< nng_socket >
struct is_expected_specialization
struct is_expected_specialization< expected_t< value_t > >
struct own
struct unexpected
struct value
Functions
template<typename value_t>
expected (value_t &&) -> expected< value_t >
template<typename enum_t>
clev::expected< void > make_expected (const int e) noexcept
Variables
template<typename expected_t>
constexpr bool is_expected_specialization_v
Function Documentation
expected()
template<typename value_t> clev::expected (value_t &&) -> expected< value_t >
Referenced by clev::expected< value_t >::transform_to(), clev::expected< value_t >::transform_to(), and clev::expected< void >::transform_to().
make_expected()
template<typename enum_t> clev::expected< void > clev::make_expected (const int e) inline noexcept
Definition at line 236 of file err.h.
{
  if (e != 0)
    return clev::unexpected(static_cast<enum_t>(e));
  return {};
}
Referenced by nngxx::invoke(), and nngxx::make().
Variable Documentation
is_expected_specialization_v
template<typename expected_t> bool clev::is_expected_specialization_v inline constexpr
Initial value:
=
  is_expected_specialization<expected_t>::value
Definition at line 92 of file err.h.
Referenced by clev::expected< value_t >::and_then().