pars: pars::ev::enqueuer Class Reference
pars::ev::enqueuer Class Reference
#include <enqueuer.h>
Public Member Functions
enqueuer (dispatcher &d, runner &r)
template<internal_event_c event_t>
void queue_fire (event_t ev)
template<template< typename > typename kind_of, network_event_c event_t, network_event_c event2_t>
requires kind_c<kind_of>
void queue_fire (event_t ev, ev::metadata< kind_of, event2_t > md)
template<network_event_c event_t, net::tool_c tool_t>
void queue_fire (event_t ev, const int s_id, tool_t &t, const net::pipe &p)
template<network_event_c event_t, net::tool_c tool_t>
void queue_sent (event_t ev, int s_id, tool_t &t, net::pipe p)
template<net::tool_c tool_t>
void queue_received (nng::msg m, int s_id, tool_t &t, net::pipe p)
Detailed Description
Definition at line 42 of file enqueuer.h.
Constructor & Destructor Documentation
enqueuer()
pars::ev::enqueuer::enqueuer (dispatcher & d, runner & r) inline
Definition at line 45 of file enqueuer.h.
    : dispatcher_m{d}
    , runner_m{r}
  {
  }
Member Function Documentation
queue_fire() [1/3]
template<internal_event_c event_t> void pars::ev::enqueuer::queue_fire (event_t ev) inline
Definition at line 52 of file enqueuer.h.
  {
    dispatcher_m.queue_back(fired{std::move(ev), {}});
  }
Referenced by queue_fire(), pars::net::op::recv(), and pars::net::op::send().
queue_fire() [2/3]
template<network_event_c event_t, net::tool_c tool_t> void pars::ev::enqueuer::queue_fire (event_t ev, const int s_id, tool_t & t, const net::pipe & p) inline
Definition at line 66 of file enqueuer.h.
  {
    if constexpr (std::is_same_v<event_t, creating_pipe> ||
                  std::is_same_v<event_t, pipe_created> ||
                  std::is_same_v<event_t, pipe_removed>)
    {
      if (dispatcher_m.terminating())
      {
        p.close();
        return;
      }
      if constexpr (std::is_same_v<event_t, creating_pipe>)
        runner_m.add_pipe(p);
      else if constexpr (std::is_same_v<event_t, pipe_removed>)
        runner_m.remove_pipe(p);
      if (!runner_m.can_exec(s_id, spec<fired<event_t>>::hash))
        return;
    }
    dispatcher_m.queue_back(fired{std::move(ev), {s_id, t, p}});
  }
References pars::net::pipe::close().
queue_fire() [3/3]
template<template< typename > typename kind_of, network_event_c event_t, network_event_c event2_t> requires kind_c<kind_of> void pars::ev::enqueuer::queue_fire (event_t ev, ev::metadata< kind_of, event2_t > md) inline
Definition at line 60 of file enqueuer.h.
  {
    queue_fire(ev, md.pipe().socket_id(), md.tool(), md.pipe());
  }
References queue_fire().
queue_received()
template<net::tool_c tool_t> void pars::ev::enqueuer::queue_received (nng::msg m, int s_id, tool_t & t, net::pipe p) inline
Definition at line 98 of file enqueuer.h.
  {
    dispatcher_m.queue_back(received{std::move(m), {s_id, t, p}});
  }
Referenced by pars::net::op::recv().
queue_sent()
template<network_event_c event_t, net::tool_c tool_t> void pars::ev::enqueuer::queue_sent (event_t ev, int s_id, tool_t & t, net::pipe p) inline
Definition at line 92 of file enqueuer.h.
  {
    dispatcher_m.queue_back(sent{std::move(ev), {s_id, t, p}});
  }
Referenced by pars::net::op::send().
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/ev/enqueuer.h