pars: pars::net::req Class Reference
pars::net::req Class Reference
Represents an nng_req protocol.
#include <req.h>
Public Member Functions
req (ev::hf_registry &h, ev::enqueuer &r)
Construct a req.
socket & sock ()
Get the socket.
const socket & sock () const
Get the socket.
context_registry & ctxs ()
Get the context_registry.
void stop ()
Stop socket and all contexts.
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t>
requires ev::kind_c<kind_of>
void on (void(class_t::*hf)(ev::hf_arg< kind_of, event_t >), class_t *self)
template<template< typename > typename kind_of, ev::event_c event_t>
requires ev::kind_c<kind_of>
void insert (ev::handler_f< kind_of, event_t > hf)
Detailed Description
Represents an nng_req protocol.
Definition at line 46 of file req.h.
Constructor & Destructor Documentation
req()
pars::net::req::req (ev::hf_registry & h, ev::enqueuer & r) inline
Construct a req.
Definition at line 50 of file req.h.
    : sock_m{r, nng::req::v0::open()}
    , ctx_registry_m{r, sock_m}
    , hf_registry_m{h}
  {
  }
References req().
Referenced by req().
Member Function Documentation
ctxs()
context_registry & pars::net::req::ctxs () inline
Get the context_registry.
Definition at line 64 of file req.h.
{ return ctx_registry_m; }
insert()
template<template< typename > typename kind_of, ev::event_c event_t> requires ev::kind_c<kind_of> void pars::net::req::insert (ev::handler_f< kind_of, event_t > hf) inline
Definition at line 84 of file req.h.
  {
    hf_registry_m.insert(sock_m.id(), std::move(hf));
  }
Referenced by on().
on()
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t> requires ev::kind_c<kind_of> void pars::net::req::on (void(class_t::* hf)(ev::hf_arg< kind_of, event_t >), class_t * self) inline
Definition at line 77 of file req.h.
  {
    insert<kind_of, event_t>(ev::make_hf(hf, self));
  }
References insert(), and pars::ev::make_hf().
sock() [1/2]
socket & pars::net::req::sock () inline
Get the socket.
Definition at line 58 of file req.h.
{ return sock_m; }
sock() [2/2]
const socket & pars::net::req::sock () const inline
Get the socket.
Definition at line 61 of file req.h.
{ return sock_m; }
stop()
void pars::net::req::stop () inline
Stop socket and all contexts.
Definition at line 67 of file req.h.
  {
    sock_m.stop();
    ctx_registry_m.stop_all();
  }
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/req.h