pars: pars::net::context_registry Class Reference
pars::net::context_registry Class Reference
#include <context_registry.h>
Public Member Functions
context_registry (ev::enqueuer &r, net::socket &s)
void stop_all ()
auto & emplace ()
context & of (const net::tool_view &t)
void start_recv (int num_ctxs)
Detailed Description
Definition at line 42 of file context_registry.h.
Constructor & Destructor Documentation
context_registry()
pars::net::context_registry::context_registry (ev::enqueuer & r, net::socket & s) inline
Definition at line 45 of file context_registry.h.
    : router_m{r}
    , sock_m{s}
  {
  }
Member Function Documentation
emplace()
auto & pars::net::context_registry::emplace () inline
Definition at line 57 of file context_registry.h.
  {
    auto ctx = sock_m.make_ctx();
    auto id = ctx.id();
    auto res = ctx_map_m.emplace(
      std::piecewise_construct, std::forward_as_tuple(id),
      std::forward_as_tuple(router_m, std::move(ctx), sock_m));
    if (!res.second)
      throw new std::runtime_error("Unable to emplace a context");
    return res.first->second;
  }
Referenced by start_recv().
of()
context & pars::net::context_registry::of (const net::tool_view & t) inline
Definition at line 73 of file context_registry.h.
  {
    if (t.type() != typeid(nng::ctx_view))
      throw new std::runtime_error("We need a context here");
    if (ctx_map_m.find(t.id()) == ctx_map_m.end())
      throw new std::runtime_error(fmt::format("Unknown context {}", t.id()));
    return ctx_map_m.at(t.id());
  }
References pars::net::tool_view::id(), and pars::net::tool_view::type().
start_recv()
void pars::net::context_registry::start_recv (int num_ctxs) inline
Definition at line 84 of file context_registry.h.
  {
    for (int i = 0; i < num_ctxs; ++i)
      emplace().recv();
  }
References emplace().
stop_all()
void pars::net::context_registry::stop_all () inline
Definition at line 51 of file context_registry.h.
  {
    for (auto& c : ctx_map_m)
      c.second.stop();
  }
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/context_registry.h