pars: pars::app::resources< key_t, resource_t, mutex_t > Class Template Reference
pars::app::resources< key_t, resource_t, mutex_t > Class Template Reference
#include <resources.h>
Public Types
using key_type = key_t
using resource_type = resource_t
using mutex_type = mutex_t
Public Member Functions
resources ()
std::size_t count ()
bool contains (const key_type key)
template<class... args_t>
auto find_or_emplace (const key_type key, args_t &&... args)
template<class... args_t>
auto emplace (const key_type key, args_t &&... args)
auto locked_resource (const key_type k) -> locked< resource_type, mutex_type, key_type >
void delete_resource (key_type k)
Detailed Description
template<typename key_t, typename resource_t, typename mutex_t = std::mutex>
class pars::app::resources< key_t, resource_t, mutex_t >
Definition at line 83 of file resources.h.
Member Typedef Documentation
key_type
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> using pars::app::resources< key_t, resource_t, mutex_t >::key_type = key_t
Definition at line 86 of file resources.h.
mutex_type
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> using pars::app::resources< key_t, resource_t, mutex_t >::mutex_type = mutex_t
Definition at line 88 of file resources.h.
resource_type
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> using pars::app::resources< key_t, resource_t, mutex_t >::resource_type = resource_t
Definition at line 87 of file resources.h.
Constructor & Destructor Documentation
resources()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> pars::app::resources< key_t, resource_t, mutex_t >::resources () inline
Definition at line 90 of file resources.h.
{}
Member Function Documentation
contains()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> bool pars::app::resources< key_t, resource_t, mutex_t >::contains (const key_type key) inline
Definition at line 99 of file resources.h.
  {
    auto guard = std::lock_guard{mtx_m};
    return resources_m.contains(key);
  }
count()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> std::size_t pars::app::resources< key_t, resource_t, mutex_t >::count () inline
Definition at line 92 of file resources.h.
  {
    auto guard = std::lock_guard{mtx_m};
    return resources_m.size();
  }
delete_resource()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> void pars::app::resources< key_t, resource_t, mutex_t >::delete_resource (key_type k) inline
Definition at line 146 of file resources.h.
  {
    auto guard = std::lock_guard{mtx_m};
    {
      auto guard = std::lock_guard{mtxs_m.at(k)};
      resources_m.erase(k);
    }
    mtxs_m.erase(k);
  }
emplace()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> template<class... args_t> auto pars::app::resources< key_t, resource_t, mutex_t >::emplace (const key_type key, args_t &&... args) inline
Definition at line 115 of file resources.h.
  {
    auto guard = std::lock_guard{mtx_m};
    auto mtx = mtxs_m.emplace(std::piecewise_construct,
                              std::forward_as_tuple(key), std::tuple());
    if (!mtx.second)
      throw std::runtime_error(fmt::format(
        "Unable to emplace a new Resource Mutex [key: 0x{:X}]", key));
    auto res = resources_m.emplace(key, std::forward<args_t>(args)...);
    if (!res.second)
    {
      mtxs_m.erase(mtx.first);
      throw std::runtime_error(
        fmt::format("Unable to emplace a new Resource [key: 0x{:X}]", key));
    }
    pars::debug(SL, lf::app, "Emplaced Resource [key: 0x{:X}]", key);
    return locked{lockable{res.first->second, mtx.first->second}, key};
  }
References pars::app, pars::debug(), and SL.
Referenced by find_or_emplace().
find_or_emplace()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> template<class... args_t> auto pars::app::resources< key_t, resource_t, mutex_t >::find_or_emplace (const key_type key, args_t &&... args) inline
Definition at line 107 of file resources.h.
  {
    if (resources_m.contains(key))
      return find_locked(key, resources_m);
    return emplace(key, std::forward<args>(args)...);
  }
References emplace().
locked_resource()
template<typename key_t, typename resource_t, typename mutex_t = std::mutex> auto pars::app::resources< key_t, resource_t, mutex_t >::locked_resource (const key_type k) -> locked<resource_type, mutex_type, key_type> inline
Definition at line 140 of file resources.h.
  {
    return find_locked(k, resources_m);
  }
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/app/resources.h