pars: pars::net::socket Class Reference
pars::net::socket Class Reference
Represents an nng_socket.
#include <socket.h>
Public Member Functions
socket (ev::enqueuer &r, nng::socket &&s)
Construct a socket.
~socket ()
operator tool_view ()
void options (const socket_opt opts)
socket_opt options () const
void dial (const char *addr)
void listen (const char *addr)
void connect (const char *addr, const cmode mode)
nng::ctx make_ctx () const
void send_aio (nng::aio_view a)
void recv_aio (nng::aio_view a)
template<ev::event_c event_t>
void send (event_t ev, pipe p={})
void recv ()
void stop ()
int id () const
int socket_id () const
const char * proto_name () const
auto format_to (fmt::format_context &ctx) const -> decltype(ctx.out())
Detailed Description
Represents an nng_socket.
Definition at line 70 of file socket.h.
Constructor & Destructor Documentation
socket()
pars::net::socket::socket (ev::enqueuer & r, nng::socket && s) inline
Construct a socket.
Definition at line 74 of file socket.h.
    : router_m{r}
    , socket_m{std::move(s)}
  {
    register_pipe_notify();
  }
~socket()
pars::net::socket::~socket () inline
Definition at line 81 of file socket.h.
{ stop(); }
References stop().
Member Function Documentation
connect()
void pars::net::socket::connect (const char * addr, const cmode mode) inline
Definition at line 114 of file socket.h.
  {
    switch (mode)
    {
    case cmode::dial:
      dial(addr);
      break;
    case cmode::listen:
      listen(addr);
      break;
    }
  }
References pars::net::dial, and pars::net::listen.
dial()
void pars::net::socket::dial (const char * addr) inline
Definition at line 110 of file socket.h.
{ emplace_dialer(addr).start(); }
format_to()
auto pars::net::socket::format_to (fmt::format_context & ctx) const -> decltype(ctx.out()) inline
Definition at line 158 of file socket.h.
  {
    return fmt::format_to(ctx.out(), "Socket #{}-{}", id(), proto_name());
  }
References proto_name().
id()
int pars::net::socket::id () const inline
Definition at line 145 of file socket.h.
{ return socket_m.id(); }
Referenced by socket_id().
listen()
void pars::net::socket::listen (const char * addr) inline
Definition at line 112 of file socket.h.
{ emplace_listener(addr).start(); }
make_ctx()
nng::ctx pars::net::socket::make_ctx () const inline
Definition at line 129 of file socket.h.
{ return nng::make_ctx(socket_m); }
operator tool_view()
pars::net::socket::operator tool_view () inline
Definition at line 83 of file socket.h.
{ return tool_view{socket_m}; }
options() [1/2]
socket_opt pars::net::socket::options () const inline
Definition at line 100 of file socket.h.
  {
    return {
      .recv_timeout = socket_m.get_opt_ms(NNG_OPT_RECVTIMEO),
      .send_timeout = socket_m.get_opt_ms(NNG_OPT_SENDTIMEO),
      .req_resend_time = socket_m.get_opt_ms(NNG_OPT_REQ_RESENDTIME),
      .req_resend_tick = socket_m.get_opt_ms(NNG_OPT_REQ_RESENDTICK),
    };
  }
options() [2/2]
void pars::net::socket::options (const socket_opt opts) inline
Definition at line 85 of file socket.h.
  {
    if (opts.recv_timeout)
      socket_m.set_opt_ms(NNG_OPT_RECVTIMEO, *opts.recv_timeout);
    if (opts.send_timeout)
      socket_m.set_opt_ms(NNG_OPT_SENDTIMEO, *opts.send_timeout);
    if (opts.req_resend_time)
      socket_m.set_opt_ms(NNG_OPT_REQ_RESENDTIME, *opts.send_timeout);
    if (opts.req_resend_tick)
      socket_m.set_opt_ms(NNG_OPT_REQ_RESENDTICK, *opts.send_timeout);
  }
References pars::net::socket_opt::recv_timeout, pars::net::socket_opt::req_resend_tick, pars::net::socket_opt::req_resend_time, and pars::net::socket_opt::send_timeout.
proto_name()
const char * pars::net::socket::proto_name () const inline
Definition at line 149 of file socket.h.
  {
    const char* proto_name_ptr;
    nng_socket_proto_name(socket_m.get(), &proto_name_ptr);
    return proto_name_ptr;
  }
Referenced by format_to().
recv()
void pars::net::socket::recv () inline
Definition at line 141 of file socket.h.
{ op_m.recv(router_m, *this); }
recv_aio()
void pars::net::socket::recv_aio (nng::aio_view a) inline
Definition at line 133 of file socket.h.
{ socket_m.recv(a); }
send()
template<ev::event_c event_t> void pars::net::socket::send (event_t ev, pipe p = {}) inline
Definition at line 136 of file socket.h.
                                 {})
  {
    op_m.send(router_m, *this, p, ev);
  }
send_aio()
void pars::net::socket::send_aio (nng::aio_view a) inline
Definition at line 131 of file socket.h.
{ socket_m.send(a); }
socket_id()
int pars::net::socket::socket_id () const inline
Definition at line 147 of file socket.h.
{ return id(); }
References id().
stop()
void pars::net::socket::stop () inline
Definition at line 143 of file socket.h.
{ op_m.stop(); }
Referenced by ~socket().
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/socket.h