pars: pars::ev::job Class Reference
pars::ev::job Class Reference
#include <job.h>
Public Member Functions
job (std::size_t j_id, int s_id, std::size_t h, std::any ke)
job (const job &)=delete
job (job &&)=default
job & operator= (const job &)=delete
job & operator= (job &&j)=default
template<template< typename > typename kind_of, event_c event_t>
requires (!is_same_kind_v<kind_of, received> || std::is_same_v<event_t, nng::msg>)
kind_of< event_t > event ()
template<template< typename > typename kind_of, event_c event_t>
requires (is_same_kind_v<kind_of, received> && !std::is_same_v<event_t, nng::msg>)
received< event_t > event ()
std::size_t id () const
int socket_id () const
std::size_t spec_hash () const
auto format_to (fmt::format_context &ctx) const -> decltype(ctx.out())
void set_id (std::size_t id)
Detailed Description
Definition at line 46 of file job.h.
Constructor & Destructor Documentation
job() [1/3]
pars::ev::job::job (std::size_t j_id, int s_id, std::size_t h, std::any ke) inline
Definition at line 49 of file job.h.
    : id_m{j_id}
    , socket_id_m{s_id}
    , spec_hash_m{h}
    , event_kind_m{std::move(ke)}
  {
  }
Referenced by job(), job(), operator=(), and operator=().
job() [2/3]
pars::ev::job::job (const job &) delete
References job().
job() [3/3]
pars::ev::job::job (job &&) default
References job().
Member Function Documentation
event() [1/2]
template<template< typename > typename kind_of, event_c event_t> requires (!is_same_kind_v<kind_of, received> || std::is_same_v<event_t, nng::msg>) kind_of< event_t > pars::ev::job::event () inline
Definition at line 68 of file job.h.
  {
    return std::any_cast<kind_of<event_t>>(std::move(event_kind_m));
  }
Referenced by event(), and pars::ev::hf_registry::insert().
event() [2/2]
template<template< typename > typename kind_of, event_c event_t> requires (is_same_kind_v<kind_of, received> && !std::is_same_v<event_t, nng::msg>) received< event_t > pars::ev::job::event () inline
Definition at line 76 of file job.h.
  {
    // get the received<nng::msg>
    auto r = event<received, nng::msg>();
    auto& md = r.metadata();
    // return a received<event_t>
    return received{
      serialize::to_event<event_t>(r.event()),
      metadata<received, event_t>{md.socket_id(), md.tool(), md.pipe()}};
  }
References event(), and pars::ev::serialize::to_event().
format_to()
auto pars::ev::job::format_to (fmt::format_context & ctx) const -> decltype(ctx.out()) inline
Definition at line 95 of file job.h.
  {
    return fmt::format_to(ctx.out(), "spec:0x{:X}", spec_hash());
  }
References spec_hash().
id()
std::size_t pars::ev::job::id () const inline
Definition at line 89 of file job.h.
{ return id_m; }
Referenced by pars::ev::runner::exec(), pars::ev::hf_registry::insert(), set_id(), and pars::ev::runner::start_thread().
operator=() [1/2]
job & pars::ev::job::operator= (const job &) delete
References job().
operator=() [2/2]
job & pars::ev::job::operator= (job && j) default
References pars::ev::is_same_kind_v, and job().
set_id()
void pars::ev::job::set_id (std::size_t id) inline
Definition at line 100 of file job.h.
{ id_m = id; }
References id().
socket_id()
int pars::ev::job::socket_id () const inline
Definition at line 91 of file job.h.
{ return socket_id_m; }
Referenced by pars::ev::runner::exec(), and pars::ev::runner::start_thread().
spec_hash()
std::size_t pars::ev::job::spec_hash () const inline
Definition at line 93 of file job.h.
{ return spec_hash_m; }
Referenced by pars::ev::runner::exec(), and format_to().
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/ev/job.h