pars: pars::net::pull Class Reference
pars::net::pull Class Reference
Represents an nng_pull protocol.
#include <pull.h>
Public Member Functions
pull (ev::hf_registry &h, ev::enqueuer &r)
Construct a pull.
socket & sock ()
Get the socket.
const socket & sock () const
Get the socket.
void stop ()
Stop socket.
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t>
requires ev::kind_c<kind_of>
void on (void(class_t::*hf)(ev::hf_arg< kind_of, event_t >), class_t *self)
template<template< typename > typename kind_of, ev::event_c event_t>
requires ev::kind_c<kind_of>
void insert (ev::handler_f< kind_of, event_t > hf)
Detailed Description
Represents an nng_pull protocol.
Definition at line 45 of file pull.h.
Constructor & Destructor Documentation
pull()
pars::net::pull::pull (ev::hf_registry & h, ev::enqueuer & r) inline
Construct a pull.
Definition at line 49 of file pull.h.
    : sock_m{r, nng::pull::v0::open()}
    , hf_registry_m{h}
  {
  }
References pull().
Referenced by pull().
Member Function Documentation
insert()
template<template< typename > typename kind_of, ev::event_c event_t> requires ev::kind_c<kind_of> void pars::net::pull::insert (ev::handler_f< kind_of, event_t > hf) inline
Definition at line 74 of file pull.h.
  {
    hf_registry_m.insert(sock_m.id(), std::move(hf));
  }
Referenced by on().
on()
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t> requires ev::kind_c<kind_of> void pars::net::pull::on (void(class_t::* hf)(ev::hf_arg< kind_of, event_t >), class_t * self) inline
Definition at line 67 of file pull.h.
  {
    insert<kind_of, event_t>(ev::make_hf(hf, self));
  }
References insert(), and pars::ev::make_hf().
sock() [1/2]
socket & pars::net::pull::sock () inline
Get the socket.
Definition at line 56 of file pull.h.
{ return sock_m; }
sock() [2/2]
const socket & pars::net::pull::sock () const inline
Get the socket.
Definition at line 59 of file pull.h.
{ return sock_m; }
stop()
void pars::net::pull::stop () inline
Stop socket.
Definition at line 62 of file pull.h.
{ sock_m.stop(); }
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/pull.h