pars: pars_example::resource::pipe_resource Struct Reference
pars_example::resource::pipe_resource Struct Reference
#include <common.h>
Public Member Functions
pipe_resource (pipe_state s)
pipe_resource (const pipe_resource &)=delete
pipe_resource (pipe_resource &&)=delete
void save_tool (net::tool_view t)
const net::tool_view & load_tool () const
Public Attributes
app::state_machine< pipe_state > state
Detailed Description
Definition at line 71 of file common.h.
Constructor & Destructor Documentation
pipe_resource() [1/3]
pars_example::resource::pipe_resource::pipe_resource (pipe_state s) inline
Definition at line 75 of file common.h.
    : state{s}
  {
  }
References state.
Referenced by pipe_resource(), and pipe_resource().
pipe_resource() [2/3]
pars_example::resource::pipe_resource::pipe_resource (const pipe_resource &) delete
References pipe_resource().
pipe_resource() [3/3]
pars_example::resource::pipe_resource::pipe_resource (pipe_resource &&) delete
References pipe_resource().
Member Function Documentation
load_tool()
const net::tool_view & pars_example::resource::pipe_resource::load_tool () const inline
Definition at line 86 of file common.h.
{ return *tool_m; }
save_tool()
void pars_example::resource::pipe_resource::save_tool (net::tool_view t) inline
Definition at line 84 of file common.h.
{ tool_m.emplace(t); }
Member Data Documentation
state
app::state_machine<pipe_state> pars_example::resource::pipe_resource::state
Definition at line 73 of file common.h.
Referenced by pipe_resource().
The documentation for this struct was generated from the following file:
/home/runner/work/pars/pars/example/common.h