pars: pars::net::push Class Reference
pars::net::push Class Reference
Represents an nng_push protocol.
#include <push.h>
Public Member Functions
push (ev::hf_registry &h, ev::enqueuer &r)
Construct a push.
socket & sock ()
Get the socket.
const socket & sock () const
Get the socket.
void stop ()
Stop socket.
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t>
requires ev::kind_c<kind_of>
void on (void(class_t::*hf)(ev::hf_arg< kind_of, event_t >), class_t *self)
template<template< typename > typename kind_of, ev::event_c event_t>
requires ev::kind_c<kind_of>
void insert (ev::handler_f< kind_of, event_t > hf)
Detailed Description
Represents an nng_push protocol.
Definition at line 44 of file push.h.
Constructor & Destructor Documentation
push()
pars::net::push::push (ev::hf_registry & h, ev::enqueuer & r) inline
Construct a push.
Definition at line 48 of file push.h.
    : sock_m{r, nng::push::v0::open()}
    , hf_registry_m{h}
  {
  }
References push().
Referenced by push().
Member Function Documentation
insert()
template<template< typename > typename kind_of, ev::event_c event_t> requires ev::kind_c<kind_of> void pars::net::push::insert (ev::handler_f< kind_of, event_t > hf) inline
Definition at line 73 of file push.h.
  {
    hf_registry_m.insert(sock_m.id(), std::move(hf));
  }
Referenced by on().
on()
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t> requires ev::kind_c<kind_of> void pars::net::push::on (void(class_t::* hf)(ev::hf_arg< kind_of, event_t >), class_t * self) inline
Definition at line 66 of file push.h.
  {
    insert<kind_of, event_t>(ev::make_hf(hf, self));
  }
References insert(), and pars::ev::make_hf().
sock() [1/2]
socket & pars::net::push::sock () inline
Get the socket.
Definition at line 55 of file push.h.
{ return sock_m; }
sock() [2/2]
const socket & pars::net::push::sock () const inline
Get the socket.
Definition at line 58 of file push.h.
{ return sock_m; }
stop()
void pars::net::push::stop () inline
Stop socket.
Definition at line 61 of file push.h.
{ sock_m.stop(); }
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/push.h