pars: pars::net::tool_view Class Reference
pars::net::tool_view Class Reference
Represents an nng_socket or nng_ctx view.
#include <tool_view.h>
Public Member Functions
tool_view (nngxx::ctx_view c)
Construct a tool_view from an nng_ctx view.
tool_view (nngxx::socket_view s)
Construct a tool_view from an nng_socket view.
const std::type_info & type () const
Get the std::type_info of the underlying variant.
const char * who () const
Get a string that represents the type of the underlying variant.
int id () const
The id of the underlying variant.
auto format_to (fmt::format_context &ctx) const -> decltype(ctx.out())
Formatter for debugging purpose.
Detailed Description
Represents an nng_socket or nng_ctx view.
Definition at line 48 of file tool_view.h.
Constructor & Destructor Documentation
tool_view() [1/2]
pars::net::tool_view::tool_view (nngxx::ctx_view c) inline explicit
Construct a tool_view from an nng_ctx view.
Definition at line 52 of file tool_view.h.
    : tool_m{c}
  {
  }
tool_view() [2/2]
pars::net::tool_view::tool_view (nngxx::socket_view s) inline explicit
Construct a tool_view from an nng_socket view.
Definition at line 58 of file tool_view.h.
    : tool_m{s}
  {
  }
Member Function Documentation
format_to()
auto pars::net::tool_view::format_to (fmt::format_context & ctx) const -> decltype(ctx.out()) inline
Formatter for debugging purpose.
Definition at line 79 of file tool_view.h.
  {
    return fmt::format_to(ctx.out(), "{} #{}", who(), id());
  }
References who().
id()
int pars::net::tool_view::id () const inline
The id of the underlying variant.
Definition at line 73 of file tool_view.h.
  {
    return std::visit([](const auto& t) { return t.id(); }, tool_m);
  }
Referenced by pars::net::context_registry::of().
type()
const std::type_info & pars::net::tool_view::type () const inline
Get the std::type_info of the underlying variant.
Definition at line 64 of file tool_view.h.
  {
    return std::visit([](auto& t) { return std::ref(typeid(t)); }, tool_m);
  }
Referenced by pars::net::context_registry::of().
who()
const char * pars::net::tool_view::who () const inline
Get a string that represents the type of the underlying variant.
Definition at line 70 of file tool_view.h.
{ return tool_m.index() == 0 ? "Context" : "Socket"; }
Referenced by format_to().
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/tool_view.h