pars: pars::net::rep Class Reference
pars::net::rep Class Reference
Represents an nng_rep protocol.
#include <rep.h>
Public Member Functions
rep (ev::hf_registry &h, ev::enqueuer &r)
Construct a rep.
socket & sock ()
Get the socket.
const socket & sock () const
Get the socket.
context_registry & ctxs ()
Get the context_registry.
void stop ()
Stop socket and all contexts.
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t>
requires ev::kind_c<kind_of>
void on (void(class_t::*hf)(ev::hf_arg< kind_of, event_t >), class_t *self)
template<template< typename > typename kind_of, ev::event_c event_t>
requires ev::kind_c<kind_of>
void insert (ev::handler_f< kind_of, event_t > hf)
Detailed Description
Represents an nng_rep protocol.
Definition at line 44 of file rep.h.
Constructor & Destructor Documentation
rep()
pars::net::rep::rep (ev::hf_registry & h, ev::enqueuer & r) inline
Construct a rep.
Definition at line 48 of file rep.h.
    : sock_m{r, nngxx::rep::v0::make_socket().value_or_abort()}
    , ctx_registry_m{r, sock_m}
    , hf_registry_m{h}
  {
  }
References rep().
Referenced by rep().
Member Function Documentation
ctxs()
context_registry & pars::net::rep::ctxs () inline
Get the context_registry.
Definition at line 62 of file rep.h.
{ return ctx_registry_m; }
insert()
template<template< typename > typename kind_of, ev::event_c event_t> requires ev::kind_c<kind_of> void pars::net::rep::insert (ev::handler_f< kind_of, event_t > hf) inline
Definition at line 82 of file rep.h.
  {
    hf_registry_m.insert(sock_m.id(), std::move(hf));
  }
Referenced by on().
on()
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t> requires ev::kind_c<kind_of> void pars::net::rep::on (void(class_t::* hf)(ev::hf_arg< kind_of, event_t >), class_t * self) inline
Definition at line 75 of file rep.h.
  {
    insert<kind_of, event_t>(ev::make_hf(hf, self));
  }
References insert(), and pars::ev::make_hf().
sock() [1/2]
socket & pars::net::rep::sock () inline
Get the socket.
Definition at line 56 of file rep.h.
{ return sock_m; }
sock() [2/2]
const socket & pars::net::rep::sock () const inline
Get the socket.
Definition at line 59 of file rep.h.
{ return sock_m; }
stop()
void pars::net::rep::stop () inline
Stop socket and all contexts.
Definition at line 65 of file rep.h.
  {
    sock_m.stop();
    ctx_registry_m.stop_all();
  }
The documentation for this class was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/net/rep.h