pars: nngxx Namespace Reference
nngxx Namespace Reference
Namespaces
namespace pull
namespace push
namespace rep
namespace req
Classes
struct msg_body
struct msg_header
struct opt_getter
struct opt_setter
struct opt_to_nng_type
struct opt_to_nng_type< opt::recvtimeo >
struct opt_to_nng_type< opt::req_resend_tick >
struct opt_to_nng_type< opt::req_resend_time >
struct opt_to_nng_type< opt::sendtimeo >
struct opt_to_nng_type< opt::sockname >
struct value
Concepts
concept nng_value_c
concept nng_with_set_opt_c
concept nng_with_get_opt_c
concept nng_c
concept uint_c
concept move_only_constructible_c
concept move_only_assignable_c
concept movable_only_c
Typedefs
using aio_view = clev::iface<nng_aio*>
using aio = clev::own<nng_aio*>
using ctx_view = clev::iface<nng_ctx>
using ctx = clev::own<nng_ctx>
using dialer_view = clev::iface<nng_dialer>
using dialer = clev::own<nng_dialer>
using listener_view = clev::iface<nng_listener>
using listener = clev::own<nng_listener>
using msg_view = clev::iface<nng_msg*>
using msg = clev::own<nng_msg*>
template<opt o>
using opt_to_nng_type_t = opt_to_nng_type<o>::return_type
using pipe_view = clev::iface<nng_pipe>
using socket_view = clev::iface<nng_socket>
using socket = clev::own<nng_socket>
Enumerations
enum class err {
success = 0 , intr = NNG_EINTR , nomem = NNG_ENOMEM , inval = NNG_EINVAL ,
busy = NNG_EBUSY , timedout = NNG_ETIMEDOUT , connrefused = NNG_ECONNREFUSED , closed = NNG_ECLOSED ,
again = NNG_EAGAIN , notsup = NNG_ENOTSUP , addrinuse = NNG_EADDRINUSE , state = NNG_ESTATE ,
noent = NNG_ENOENT , proto = NNG_EPROTO , unreachable = NNG_EUNREACHABLE , addrinval = NNG_EADDRINVAL ,
perm = NNG_EPERM , msgsize = NNG_EMSGSIZE , connaborted = NNG_ECONNABORTED , connreset = NNG_ECONNRESET ,
canceled = NNG_ECANCELED , nofiles = NNG_ENOFILES , nospc = NNG_ENOSPC , exist = NNG_EEXIST ,
readonly = NNG_EREADONLY , writeonly = NNG_EWRITEONLY , crypto = NNG_ECRYPTO , peerauth = NNG_EPEERAUTH ,
noarg = NNG_ENOARG , ambiguous = NNG_EAMBIGUOUS , badtype = NNG_EBADTYPE , connshut = NNG_ECONNSHUT ,
internal = NNG_EINTERNAL , syserr = NNG_ESYSERR , tranerr = NNG_ETRANERR
}
enum class opt {
sockname , raw , recvbuf , sendbuf ,
recvfd , sendfd , recvtimeo , sendtimeo ,
locaddr , remaddr , url , maxttl ,
recvmaxsz , reconnmint , reconnmaxt , peergid ,
peerpid , peeruid , peerzoneid , req_resend_time ,
req_resend_tick
}
enum class opt_overload {
integer , boolean , string , size ,
sockaddr , duration , uint64
}
enum class pipe_ev { add_pre = NNG_PIPE_EV_ADD_PRE , add_post = NNG_PIPE_EV_ADD_POST , rem_post = NNG_PIPE_EV_REM_POST , num = NNG_PIPE_EV_NUM }
Functions
std::error_code make_error_code (err e) noexcept
template<typename ret_t, typename arg_t, typename... args_t>
clev::expected< std::remove_pointer_t< arg_t > > make (ret_t(*f)(arg_t, args_t...), args_t... args) noexcept
template<typename ret_t, typename... args_t>
clev::expected< void > invoke (ret_t(*f)(args_t...), args_t... args) noexcept
template<typename... args_t>
clev::expected< void > invoke (void(*f)(args_t...), args_t... args) noexcept
nng_pipe_ev cast_pipe_ev (pipe_ev ev) noexcept
pipe_ev cast_pipe_ev (nng_pipe_ev ev) noexcept
Typedef Documentation
aio
using nngxx::aio = clev::own<nng_aio*>
Definition at line 39 of file aio.h.
aio_view
using nngxx::aio_view = clev::iface<nng_aio*>
Definition at line 37 of file aio.h.
ctx
using nngxx::ctx = clev::own<nng_ctx>
Definition at line 39 of file ctx.h.
ctx_view
using nngxx::ctx_view = clev::iface<nng_ctx>
Definition at line 37 of file ctx.h.
dialer
using nngxx::dialer = clev::own<nng_dialer>
Definition at line 39 of file dialer.h.
dialer_view
using nngxx::dialer_view = clev::iface<nng_dialer>
Definition at line 37 of file dialer.h.
listener
using nngxx::listener = clev::own<nng_listener>
Definition at line 39 of file listener.h.
listener_view
using nngxx::listener_view = clev::iface<nng_listener>
Definition at line 37 of file listener.h.
msg
using nngxx::msg = clev::own<nng_msg*>
Definition at line 39 of file msg.h.
msg_view
using nngxx::msg_view = clev::iface<nng_msg*>
Definition at line 37 of file msg.h.
opt_to_nng_type_t
template<opt o> using nngxx::opt_to_nng_type_t = opt_to_nng_type<o>::return_type
Definition at line 260 of file opt.h.
pipe_view
using nngxx::pipe_view = clev::iface<nng_pipe>
Definition at line 37 of file pipe.h.
socket
using nngxx::socket = clev::own<nng_socket>
Definition at line 45 of file socket_decl.h.
socket_view
using nngxx::socket_view = clev::iface<nng_socket>
Definition at line 43 of file socket_decl.h.
Enumeration Type Documentation
err
enum class nngxx::err strong
Enumerator
success
intr
nomem
inval
busy
timedout
connrefused
closed
again
notsup
addrinuse
state
noent
proto
unreachable
addrinval
perm
msgsize
connaborted
connreset
canceled
nofiles
nospc
exist
readonly
writeonly
crypto
peerauth
noarg
ambiguous
badtype
connshut
internal
syserr
tranerr
Definition at line 74 of file err.h.
{
  success = 0,
  intr = NNG_EINTR,
  nomem = NNG_ENOMEM,
  inval = NNG_EINVAL,
  busy = NNG_EBUSY,
  timedout = NNG_ETIMEDOUT,
  connrefused = NNG_ECONNREFUSED,
  closed = NNG_ECLOSED,
  again = NNG_EAGAIN,
  notsup = NNG_ENOTSUP,
  addrinuse = NNG_EADDRINUSE,
  state = NNG_ESTATE,
  noent = NNG_ENOENT,
  proto = NNG_EPROTO,
  unreachable = NNG_EUNREACHABLE,
  addrinval = NNG_EADDRINVAL,
  perm = NNG_EPERM,
  msgsize = NNG_EMSGSIZE,
  connaborted = NNG_ECONNABORTED,
  connreset = NNG_ECONNRESET,
  canceled = NNG_ECANCELED,
  nofiles = NNG_ENOFILES,
  nospc = NNG_ENOSPC,
  exist = NNG_EEXIST,
  readonly = NNG_EREADONLY,
  writeonly = NNG_EWRITEONLY,
  crypto = NNG_ECRYPTO,
  peerauth = NNG_EPEERAUTH,
  noarg = NNG_ENOARG,
  ambiguous = NNG_EAMBIGUOUS,
  badtype = NNG_EBADTYPE,
  connshut = NNG_ECONNSHUT,
  internal = NNG_EINTERNAL,
  syserr = NNG_ESYSERR,
  tranerr = NNG_ETRANERR
};
opt
enum class nngxx::opt strong
Enumerator
sockname
raw
recvbuf
sendbuf
recvfd
sendfd
recvtimeo
sendtimeo
locaddr
remaddr
url
maxttl
recvmaxsz
reconnmint
reconnmaxt
peergid
peerpid
peeruid
peerzoneid
req_resend_time
req_resend_tick
Definition at line 38 of file opt.h.
{
  sockname,
  raw,
  // proto, // deprecated
  // protoname, // deprecated
  // peer, // deprecated
  // peername, // deprecated
  recvbuf,
  sendbuf,
  recvfd,
  sendfd,
  recvtimeo,
  sendtimeo,
  locaddr,
  remaddr,
  url,
  maxttl,
  recvmaxsz,
  reconnmint,
  reconnmaxt,
  peergid,
  peerpid,
  peeruid,
  peerzoneid,
  req_resend_time,
  req_resend_tick
};
opt_overload
enum class nngxx::opt_overload strong
Enumerator
integer
boolean
string
size
sockaddr
duration
uint64
Definition at line 67 of file opt.h.
{
  integer,
  boolean,
  string,
  size,
  sockaddr,
  duration,
  uint64
};
pipe_ev
enum class nngxx::pipe_ev strong
Enumerator
add_pre
add_post
rem_post
num
Definition at line 39 of file pipe.h.
{
  add_pre = NNG_PIPE_EV_ADD_PRE,
  add_post = NNG_PIPE_EV_ADD_POST,
  rem_post = NNG_PIPE_EV_REM_POST,
  num = NNG_PIPE_EV_NUM
};
Function Documentation
cast_pipe_ev() [1/2]
pipe_ev nngxx::cast_pipe_ev (nng_pipe_ev ev) inline noexcept
Definition at line 52 of file pipe.h.
{
  return static_cast<pipe_ev>(ev);
}
cast_pipe_ev() [2/2]
nng_pipe_ev nngxx::cast_pipe_ev (pipe_ev ev) inline noexcept
Definition at line 47 of file pipe.h.
{
  return static_cast<nng_pipe_ev>(ev);
}
invoke() [1/2]
template<typename ret_t, typename... args_t> clev::expected< void > nngxx::invoke (ret_t(* f)(args_t...), args_t... args) inline nodiscard noexcept
Definition at line 123 of file err.h.
{
  return clev::make_expected<err>(f(args...));
}
References clev::make_expected().
Referenced by nngxx::msg_body::append(), nngxx::msg_body::chop(), nngxx::msg_body::chop(), nngxx::opt_getter< opt_v, nng_t >::operator()(), nngxx::opt_setter< opt_v, nng_t >::operator()(), nngxx::msg_body::trim(), and nngxx::msg_body::trim().
invoke() [2/2]
template<typename... args_t> clev::expected< void > nngxx::invoke (void(* f)(args_t...), args_t... args) inline nodiscard noexcept
Definition at line 130 of file err.h.
{
  f(args...);
  return {};
}
make()
template<typename ret_t, typename arg_t, typename... args_t> clev::expected< std::remove_pointer_t< arg_t > > nngxx::make (ret_t(* f)(arg_t, args_t...), args_t... args) inline nodiscard noexcept
Definition at line 115 of file err.h.
{
  std::remove_pointer_t<arg_t> x;
  return clev::make_expected<err>(f(&x, args...)).transform_to(std::move(x));
}
References clev::make_expected(), and clev::expected< void >::transform_to().
make_error_code()
std::error_code nngxx::make_error_code (err e) inline nodiscard noexcept
Definition at line 59 of file err.h.
{
  return std::error_code(static_cast<int>(e), error_category());
}