pars: pars::ev::hf_registry Struct Reference
pars::ev::hf_registry Struct Reference
#include <hf_registry.h>
Public Member Functions
hf_registry (runner &r)
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t>
requires ev::kind_c<kind_of>
void on (void(class_t::*mem_fn)(hf_arg< kind_of, event_t >), class_t *self)
template<template< typename > typename kind_of, event_c event_t>
requires kind_c<kind_of>
void insert (handler_f< kind_of, event_t > hf)
template<template< typename > typename kind_of, event_c event_t>
requires kind_c<kind_of>
void insert (int s_id, handler_f< kind_of, event_t > hf)
Insert an handler_f for a kind_of<event_t> on a socket s_id.
Detailed Description
Definition at line 49 of file hf_registry.h.
Constructor & Destructor Documentation
hf_registry()
pars::ev::hf_registry::hf_registry (runner & r) inline
Definition at line 52 of file hf_registry.h.
    : runner_m{r}
  {
  }
Member Function Documentation
insert() [1/2]
template<template< typename > typename kind_of, event_c event_t> requires kind_c<kind_of> void pars::ev::hf_registry::insert (handler_f< kind_of, event_t > hf) inline
Definition at line 67 of file hf_registry.h.
  {
    insert(0, std::move(hf));
  }
References insert().
Referenced by insert(), and on().
insert() [2/2]
template<template< typename > typename kind_of, event_c event_t> requires kind_c<kind_of> void pars::ev::hf_registry::insert (int s_id, handler_f< kind_of, event_t > hf)
Insert an handler_f for a kind_of<event_t> on a socket s_id.
Definition at line 40 of file hf_registry__insert.h.
{
  auto hf_ptr = std::make_shared<handler_f<kind_of, event_t>>(std::move(hf));
  auto guard = std::lock_guard{mtx_m};
  if constexpr (async_kind_c<kind_of<event_t>>)
  {
    return insert_jhf<kind_of, event_t>(s_id, [&, hf_ptr](job j) {
      auto task = std::packaged_task([hf_ptr](std::stop_token tk, job j) {
        auto ke = j.event<kind_of, event_t>();
        auto& md = ke.md();
        md.set_job_id(j.id());
        md.set_stop_token(tk);
        (*hf_ptr)(std::move(ke));
      });
      runner_m.start_thread(spec<kind_of<event_t>>::hash, std::move(task),
                            std::move(j));
    });
  }
  else
  {
    return insert_jhf<kind_of, event_t>(s_id, [hf_ptr](job j) {
      auto ke = j.event<kind_of, event_t>();
      ke.md().set_job_id(j.id());
      (*hf_ptr)(ke);
    });
  }
}
References pars::ev::job::event(), and pars::ev::job::id().
on()
template<template< typename > typename kind_of, ev::event_c event_t, typename class_t> requires ev::kind_c<kind_of> void pars::ev::hf_registry::on (void(class_t::* mem_fn)(hf_arg< kind_of, event_t >), class_t * self) inline
Definition at line 60 of file hf_registry.h.
  {
    insert<kind_of, event_t>(make_hf(mem_fn, self));
  }
References insert(), and pars::ev::make_hf().
The documentation for this struct was generated from the following files:
/home/runner/work/pars/pars/lib/include/pars/ev/hf_registry.h
/home/runner/work/pars/pars/lib/include/pars/ev/hf_registry__insert.h