pars: pars::ev::base_network_metadata Struct Reference
pars::ev::base_network_metadata Struct Reference
#include <metadata.h>
Public Member Functions
base_network_metadata (int s_id, net::tool_view t, net::pipe p)
const net::tool_view & tool () const
const net::pipe & pipe () const
int socket_id () const
auto format_to (fmt::format_context &ctx) const -> decltype(ctx.out())
Detailed Description
Definition at line 71 of file metadata.h.
Constructor & Destructor Documentation
base_network_metadata()
pars::ev::base_network_metadata::base_network_metadata (int s_id, net::tool_view t, net::pipe p) inline
Definition at line 73 of file metadata.h.
    : id_m{s_id}
    , tool_m{t}
    , pipe_m{p}
  {
  }
Member Function Documentation
format_to()
auto pars::ev::base_network_metadata::format_to (fmt::format_context & ctx) const -> decltype(ctx.out()) inline
Definition at line 86 of file metadata.h.
  {
    // FIXME: duplicated
    return fmt::format_to(ctx.out(), "Pipe #{:X} {} {}", pipe().id(),
                          tool().who(), tool().id());
  }
References pipe(), and tool().
pipe()
const net::pipe & pars::ev::base_network_metadata::pipe () const inline
Definition at line 82 of file metadata.h.
{ return pipe_m; }
Referenced by format_to().
socket_id()
int pars::ev::base_network_metadata::socket_id () const inline
Definition at line 84 of file metadata.h.
{ return id_m; }
tool()
const net::tool_view & pars::ev::base_network_metadata::tool () const inline
Definition at line 80 of file metadata.h.
{ return tool_m; }
Referenced by format_to().
The documentation for this struct was generated from the following file:
/home/runner/work/pars/pars/lib/include/pars/ev/metadata.h