pars: nngxx::opt_setter< opt_v, nng_t > Struct Template Reference
nngxx::opt_setter< opt_v, nng_t > Struct Template Reference
#include <opt_setter.h>
Public Types
using nng_type = nng_t
Public Member Functions
template<nng_value_c nng_value_t>
clev::expected< void > operator() (nng_type obj, nng_value_t val) noexcept
Static Public Attributes
static constexpr auto opt = opt_to_nng_value<opt_v>()
static constexpr auto overload = opt_to_nng_overload<opt_v>()
Detailed Description
template<opt opt_v, nng_with_set_opt_c nng_t>
struct nngxx::opt_setter< opt_v, nng_t >
Definition at line 40 of file opt_setter.h.
Member Typedef Documentation
nng_type
template<opt opt_v, nng_with_set_opt_c nng_t> using nngxx::opt_setter< opt_v, nng_t >::nng_type = nng_t
Definition at line 42 of file opt_setter.h.
Member Function Documentation
operator()()
template<opt opt_v, nng_with_set_opt_c nng_t> template<nng_value_c nng_value_t> clev::expected< void > nngxx::opt_setter< opt_v, nng_t >::operator() (nng_type obj, nng_value_t val) inline nodiscard noexcept
Definition at line 49 of file opt_setter.h.
  {
    int (*set)(nng_type, const char*, nng_value_t);
    if constexpr (std::is_same_v<nng_type, nng_socket>)
    {
      if constexpr (overload == opt_overload::boolean)
        set = nng_socket_set_bool;
      else if constexpr (overload == opt_overload::integer)
        set = nng_socket_set_int;
      else if constexpr (overload == opt_overload::size)
        set = nng_socket_set_size;
      else if constexpr (overload == opt_overload::uint64)
        set = nng_socket_set_uint64;
      else if constexpr (overload == opt_overload::string)
        set = nng_socket_set_string;
      else if constexpr (overload == opt_overload::duration)
        set = nng_socket_set_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        set = nng_socket_set_addr;
    }
    else if constexpr (std::is_same_v<nng_type, nng_ctx>)
    {
      if constexpr (overload == opt_overload::boolean)
        set = nng_ctx_set_bool;
      else if constexpr (overload == opt_overload::integer)
        set = nng_ctx_set_int;
      else if constexpr (overload == opt_overload::size)
        set = nng_ctx_set_size;
      else if constexpr (overload == opt_overload::uint64)
        set = nng_ctx_set_uint64;
      else if constexpr (overload == opt_overload::string)
        set = nng_ctx_set_string;
      else if constexpr (overload == opt_overload::duration)
        set = nng_ctx_set_ms;
    }
    else if constexpr (std::is_same_v<nng_type, nng_listener>)
    {
      if constexpr (overload == opt_overload::boolean)
        set = nng_listener_set_bool;
      else if constexpr (overload == opt_overload::integer)
        set = nng_listener_set_int;
      else if constexpr (overload == opt_overload::size)
        set = nng_listener_set_size;
      else if constexpr (overload == opt_overload::uint64)
        set = nng_listener_set_uint64;
      else if constexpr (overload == opt_overload::string)
        set = nng_listener_set_string;
      else if constexpr (overload == opt_overload::duration)
        set = nng_listener_set_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        set = nng_listener_set_addr;
    }
    else if constexpr (std::is_same_v<nng_type, nng_dialer>)
    {
      if constexpr (overload == opt_overload::boolean)
        set = nng_dialer_set_bool;
      else if constexpr (overload == opt_overload::integer)
        set = nng_dialer_set_int;
      else if constexpr (overload == opt_overload::size)
        set = nng_dialer_set_size;
      else if constexpr (overload == opt_overload::uint64)
        set = nng_dialer_set_uint64;
      else if constexpr (overload == opt_overload::string)
        set = nng_dialer_set_string;
      else if constexpr (overload == opt_overload::duration)
        set = nng_dialer_set_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        set = nng_dialer_set_addr;
    }
    return nngxx::invoke(set, obj, opt, val);
  }
References nngxx::boolean, nngxx::duration, nngxx::integer, nngxx::invoke(), opt, overload, nngxx::size, nngxx::sockaddr, nngxx::string, and nngxx::uint64.
Member Data Documentation
opt
template<opt opt_v, nng_with_set_opt_c nng_t> auto nngxx::opt_setter< opt_v, nng_t >::opt = opt_to_nng_value<opt_v>() static constexpr
Definition at line 44 of file opt_setter.h.
Referenced by operator()().
overload
template<opt opt_v, nng_with_set_opt_c nng_t> auto nngxx::opt_setter< opt_v, nng_t >::overload = opt_to_nng_overload<opt_v>() static constexpr
Definition at line 46 of file opt_setter.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
/home/runner/work/pars/pars/lib/include/nngxx/opt_setter.h