pars: nngxx::opt_getter< opt_v, nng_t > Struct Template Reference
nngxx::opt_getter< opt_v, nng_t > Struct Template Reference
#include <opt_getter.h>
Public Types
using nng_type = nng_t
using return_type = opt_to_nng_type_t<opt_v>
Public Member Functions
clev::expected< return_type > operator() (nng_type obj) noexcept
Static Public Attributes
static constexpr auto opt = opt_to_nng_value<opt_v>()
static constexpr auto overload = opt_to_nng_overload<opt_v>()
Detailed Description
template<opt opt_v, nng_with_get_opt_c nng_t>
struct nngxx::opt_getter< opt_v, nng_t >
Definition at line 40 of file opt_getter.h.
Member Typedef Documentation
nng_type
template<opt opt_v, nng_with_get_opt_c nng_t> using nngxx::opt_getter< opt_v, nng_t >::nng_type = nng_t
Definition at line 42 of file opt_getter.h.
return_type
template<opt opt_v, nng_with_get_opt_c nng_t> using nngxx::opt_getter< opt_v, nng_t >::return_type = opt_to_nng_type_t<opt_v>
Definition at line 48 of file opt_getter.h.
Member Function Documentation
operator()()
template<opt opt_v, nng_with_get_opt_c nng_t> clev::expected< return_type > nngxx::opt_getter< opt_v, nng_t >::operator() (nng_type obj) inline nodiscard noexcept
Definition at line 51 of file opt_getter.h.
  {
    int (*get)(nng_type, const char*, return_type*);
    if constexpr (std::is_same_v<nng_type, nng_socket>)
    {
      if constexpr (overload == opt_overload::boolean)
        get = nng_socket_get_bool;
      else if constexpr (overload == opt_overload::integer)
        get = nng_socket_get_int;
      else if constexpr (overload == opt_overload::size)
        get = nng_socket_get_size;
      else if constexpr (overload == opt_overload::uint64)
        get = nng_socket_get_uint64;
      else if constexpr (overload == opt_overload::string)
        get = nng_socket_get_string;
      else if constexpr (overload == opt_overload::duration)
        get = nng_socket_get_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        get = nng_socket_get_addr;
    }
    else if constexpr (std::is_same_v<nng_type, nng_ctx>)
    {
      if constexpr (overload == opt_overload::boolean)
        get = nng_ctx_get_bool;
      else if constexpr (overload == opt_overload::integer)
        get = nng_ctx_get_int;
      else if constexpr (overload == opt_overload::size)
        get = nng_ctx_get_size;
      else if constexpr (overload == opt_overload::uint64)
        get = nng_ctx_get_uint64;
      else if constexpr (overload == opt_overload::string)
        get = nng_ctx_get_string;
      else if constexpr (overload == opt_overload::duration)
        get = nng_ctx_get_ms;
    }
    else if constexpr (std::is_same_v<nng_type, nng_listener>)
    {
      if constexpr (overload == opt_overload::boolean)
        get = nng_listener_get_bool;
      else if constexpr (overload == opt_overload::integer)
        get = nng_listener_get_int;
      else if constexpr (overload == opt_overload::size)
        get = nng_listener_get_size;
      else if constexpr (overload == opt_overload::uint64)
        get = nng_listener_get_uint64;
      else if constexpr (overload == opt_overload::string)
        get = nng_listener_get_string;
      else if constexpr (overload == opt_overload::duration)
        get = nng_listener_get_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        get = nng_listener_get_addr;
    }
    else if constexpr (std::is_same_v<nng_type, nng_dialer>)
    {
      if constexpr (overload == opt_overload::boolean)
        get = nng_dialer_get_bool;
      else if constexpr (overload == opt_overload::integer)
        get = nng_dialer_get_int;
      else if constexpr (overload == opt_overload::size)
        get = nng_dialer_get_size;
      else if constexpr (overload == opt_overload::uint64)
        get = nng_dialer_get_uint64;
      else if constexpr (overload == opt_overload::string)
        get = nng_dialer_get_string;
      else if constexpr (overload == opt_overload::duration)
        get = nng_dialer_get_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        get = nng_dialer_get_addr;
    }
    else if constexpr (std::is_same_v<nng_type, nng_pipe>)
    {
      if constexpr (overload == opt_overload::boolean)
        get = nng_pipe_get_bool;
      else if constexpr (overload == opt_overload::integer)
        get = nng_pipe_get_int;
      else if constexpr (overload == opt_overload::size)
        get = nng_pipe_get_size;
      else if constexpr (overload == opt_overload::uint64)
        get = nng_pipe_get_uint64;
      else if constexpr (overload == opt_overload::string)
        get = nng_pipe_get_string;
      else if constexpr (overload == opt_overload::duration)
        get = nng_pipe_get_ms;
      else if constexpr (overload == opt_overload::sockaddr)
        get = nng_pipe_get_addr;
    }
    return nngxx::read<return_type>(
      std::bind(get, obj, opt, std::placeholders::_1));
  }
References nngxx::boolean, nngxx::duration, nngxx::integer, opt, overload, nngxx::read(), nngxx::size, nngxx::sockaddr, nngxx::string, and nngxx::uint64.
Member Data Documentation
opt
template<opt opt_v, nng_with_get_opt_c nng_t> auto nngxx::opt_getter< opt_v, nng_t >::opt = opt_to_nng_value<opt_v>() static constexpr
Definition at line 44 of file opt_getter.h.
Referenced by operator()().
overload
template<opt opt_v, nng_with_get_opt_c nng_t> auto nngxx::opt_getter< opt_v, nng_t >::overload = opt_to_nng_overload<opt_v>() static constexpr
Definition at line 46 of file opt_getter.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
/home/runner/work/pars/pars/lib/include/nngxx/opt_getter.h