pars: nngxx::msg_body Struct Reference
nngxx::msg_body Struct Reference
#include <msg_body.h>
Public Member Functions
msg_body (nng_msg *m) noexcept
std::size_t size () const noexcept
template<typename char_t>
char_t * data () noexcept
template<typename char_t>
const char_t * data () const noexcept
template<uint_c uint_t>
clev::expected< void > append (uint_t x) noexcept
clev::expected< void > append (const void *val, std::size_t sz) noexcept
template<uint_c uint_t>
clev::expected< void > insert (uint_t x) noexcept
clev::expected< void > insert (const void *val, std::size_t sz) noexcept
template<uint_c uint_t>
clev::expected< uint_t > trim () noexcept
clev::expected< void > trim (std::size_t sz) noexcept
template<uint_c uint_t>
clev::expected< uint_t > chop () noexcept
clev::expected< void > chop (std::size_t sz) noexcept
template<uint_c uint_t>
clev::expected< uint_t > read (const std::size_t offset=0) const noexcept
template<uint_c uint_t>
clev::expected< void > write (uint_t v, const std::size_t offset=0) noexcept
Detailed Description
Definition at line 39 of file msg_body.h.
Constructor & Destructor Documentation
msg_body()
nngxx::msg_body::msg_body (nng_msg * m) inline noexcept
Definition at line 41 of file msg_body.h.
    : m{m}
  {
  }
Member Function Documentation
append() [1/2]
clev::expected< void > nngxx::msg_body::append (const void * val, std::size_t sz) inline nodiscard noexcept
Definition at line 84 of file msg_body.h.
  {
    return nngxx::invoke(nng_msg_append, m, val, sz);
  }
References nngxx::invoke().
append() [2/2]
template<uint_c uint_t> clev::expected< void > nngxx::msg_body::append (uint_t x) inline nodiscard noexcept
Definition at line 64 of file msg_body.h.
  {
    int (*append)(nng_msg*, uint_t);
    if constexpr (std::is_same_v<uint_t, uint16_t>)
    {
      append = nng_msg_append_u16;
    }
    else if constexpr (std::is_same_v<uint_t, uint32_t>)
    {
      append = nng_msg_append_u32;
    }
    else if constexpr (std::is_same_v<uint_t, uint64_t>)
    {
      append = nng_msg_append_u64;
    }
    return nngxx::invoke(append, m, x);
  }
References append(), and nngxx::invoke().
Referenced by append().
chop() [1/2]
template<uint_c uint_t> clev::expected< uint_t > nngxx::msg_body::chop () inline nodiscard noexcept
Definition at line 146 of file msg_body.h.
  {
    uint_t x;
    int (*chop)(nng_msg*, uint_t*);
    if constexpr (std::is_same_v<uint_t, uint16_t>)
    {
      chop = nng_msg_chop_u16;
    }
    else if constexpr (std::is_same_v<uint_t, uint32_t>)
    {
      chop = nng_msg_chop_u32;
    }
    else if constexpr (std::is_same_v<uint_t, uint64_t>)
    {
      chop = nng_msg_chop_u64;
    }
    return nngxx::invoke(chop, m, &x).transform([&]() { return x; });
  }
References chop(), and nngxx::invoke().
Referenced by chop().
chop() [2/2]
clev::expected< void > nngxx::msg_body::chop (std::size_t sz) inline nodiscard noexcept
Definition at line 168 of file msg_body.h.
  {
    return nngxx::invoke(nng_msg_chop, m, sz);
  }
References nngxx::invoke().
data() [1/2]
template<typename char_t> const char_t * nngxx::msg_body::data () const inline nodiscard noexcept
Definition at line 58 of file msg_body.h.
  {
    return static_cast<const char_t*>(nng_msg_body(m));
  }
data() [2/2]
template<typename char_t> char_t * nngxx::msg_body::data () inline nodiscard noexcept
Definition at line 52 of file msg_body.h.
  {
    return static_cast<char_t*>(nng_msg_body(m));
  }
Referenced by read(), and write().
insert() [1/2]
clev::expected< void > nngxx::msg_body::insert (const void * val, std::size_t sz) inline nodiscard noexcept
Definition at line 111 of file msg_body.h.
  {
    return nngxx::invoke(nng_msg_insert, m, val, sz);
  }
References nngxx::invoke().
insert() [2/2]
template<uint_c uint_t> clev::expected< void > nngxx::msg_body::insert (uint_t x) inline nodiscard noexcept
Definition at line 91 of file msg_body.h.
  {
    int (*insert)(nng_msg*, uint_t);
    if constexpr (std::is_same_v<uint_t, uint16_t>)
    {
      insert = nng_msg_insert_u16;
    }
    else if constexpr (std::is_same_v<uint_t, uint32_t>)
    {
      insert = nng_msg_insert_u32;
    }
    else if constexpr (std::is_same_v<uint_t, uint64_t>)
    {
      insert = nng_msg_insert_u64;
    }
    return nngxx::invoke(insert, m, x);
  }
References insert(), and nngxx::invoke().
Referenced by insert().
read()
template<uint_c uint_t> clev::expected< uint_t > nngxx::msg_body::read (const std::size_t offset = 0) const inline nodiscard noexcept
Definition at line 175 of file msg_body.h.
  {
    uint_t v;
    if (offset + sizeof(decltype(v)) > size())
      return clev::unexpected{nngxx::cpp::err::invalid_memory};
    std::memcpy(&v, data<char>() + offset, sizeof(decltype(v)));
    return v;
  }
References data(), nngxx::cpp::invalid_memory, and size().
size()
std::size_t nngxx::msg_body::size () const inline nodiscard noexcept
Definition at line 46 of file msg_body.h.
  {
    return nng_msg_len(m);
  }
Referenced by read(), and write().
trim() [1/2]
template<uint_c uint_t> clev::expected< uint_t > nngxx::msg_body::trim () inline nodiscard noexcept
Definition at line 118 of file msg_body.h.
  {
    uint_t x;
    int (*trim)(nng_msg*, uint_t*);
    if constexpr (std::is_same_v<uint_t, uint16_t>)
    {
      trim = nng_msg_trim_u16;
    }
    else if constexpr (std::is_same_v<uint_t, uint32_t>)
    {
      trim = nng_msg_trim_u32;
    }
    else if constexpr (std::is_same_v<uint_t, uint64_t>)
    {
      trim = nng_msg_trim_u64;
    }
    return nngxx::invoke(trim, m, &x).transform([&]() { return x; });
  }
References nngxx::invoke(), and trim().
Referenced by trim().
trim() [2/2]
clev::expected< void > nngxx::msg_body::trim (std::size_t sz) inline nodiscard noexcept
Definition at line 140 of file msg_body.h.
  {
    return nngxx::invoke(nng_msg_trim, m, sz);
  }
References nngxx::invoke().
write()
template<uint_c uint_t> clev::expected< void > nngxx::msg_body::write (uint_t v, const std::size_t offset = 0) inline nodiscard noexcept
Definition at line 189 of file msg_body.h.
  {
    if (offset + sizeof(decltype(v)) > size())
      return clev::unexpected{nngxx::cpp::err::invalid_memory};
    std::memcpy(data<char>() + offset, static_cast<void*>(&v),
                sizeof(decltype(v)));
    return {};
  }
References data(), nngxx::cpp::invalid_memory, and size().
The documentation for this struct was generated from the following file:
/home/runner/work/pars/pars/lib/include/nngxx/msg_body.h